name: isite
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h4f5f683_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alembic=1.17.2=py313haa95532_0
  - attrs=25.4.0=pyhcf101f3_1
  - autograd=1.8.0=pyhd8ed1ab_0
  - autograd-gamma=0.5.0=pyhd8ed1ab_1
  - backports.zstd=1.2.0=py313h2a31948_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h540bb41_1
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py313h3ebfc14_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py313h5ea7bf4_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=py313haa95532_0
  - colorlog=6.10.1=py313haa95532_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cycler=0.12.1=pyhcf101f3_2
  - ecos=2.0.14=np2py313haacffc7_3
  - filelock=3.20.0=py313haa95532_0
  - fonttools=4.61.1=py313hd650c13_0
  - formulaic=1.2.1=pyhd8ed1ab_2
  - freetype=2.14.1=h57928b3_0
  - frozenlist=1.7.0=py313h0c48a3b_0
  - fsspec=2025.10.0=py313h4442805_0
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.2=py313h8598115_0
  - greenlet=3.2.4=py313h885b0b7_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=py313haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - interface_meta=1.3.0=pyhd8ed1ab_1
  - jinja2=3.1.6=py313haa95532_0
  - joblib=1.5.2=py313haa95532_0
  - kiwisolver=1.4.9=py313h1a38498_2
  - lame=3.100=hcfcfb64_1003
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libflac=1.5.0=h08124e9_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_16
  - libgomp=15.2.0=h8ee18e1_16
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libmpdec=4.0.0=h827c3e9_0
  - libogg=1.3.5=h2466b09_1
  - libopus=1.6=h6a83c73_0
  - libosqp=1.0.0=np2py312h325a191_2
  - libpng=1.6.53=h7351971_0
  - libprotobuf=5.29.3=h65a231f_1
  - libqdldl=0.1.8=he0c23c2_1
  - libsndfile=1.2.2=hc3b4fa0_2
  - libtiff=4.7.0=hfc51747_1
  - libtorch=2.7.0=cpu_mkl_h017a133_100
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=h5112557_2
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lifelines=0.30.0=pyhd8ed1ab_1
  - lightning-utilities=0.15.2=py313haa95532_0
  - mako=1.3.10=py313haa95532_0
  - markupsafe=3.0.2=py313h827c3e9_0
  - matplotlib-base=3.10.8=py313he1ded55_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpg123=1.32.9=h01009b0_0
  - mpmath=1.3.0=py313haa95532_0
  - multidict=6.7.0=py313hd650c13_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.14.0=pyhcf101f3_0
  - networkx=3.6.1=py313haa95532_0
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.3.5=py313h050da96_0
  - numpy-base=2.3.5=py313h1e017a8_0
  - openjpeg=2.5.3=h24db6dd_1
  - openssl=3.6.0=h725018a_0
  - opentelemetry-api=1.38.0=py313haa95532_0
  - optuna=4.6.0=py313hab2b47e_0
  - osqp=1.0.5=np2py313h776c0ec_4
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313h42c1672_1
  - pillow=11.3.0=py313hf455b62_3
  - pip=25.3=pyhc872135_0
  - propcache=0.3.1=py313hb4c8b1a_0
  - pthread-stubs=0.4=h0e40799_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.3.1=pyhcf101f3_0
  - pysocks=1.7.1=pyh09c184e_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.13.11=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=3_cp313
  - pytorch=2.7.0=cpu_mkl_py313he241c65_100
  - pytz=2025.2=py313haa95532_0
  - pyyaml=6.0.3=py313hb9a58be_0
  - qdldl-python=0.1.7.post5=np2py313h776c0ec_3
  - qhull=2020.2=hc790b64_5
  - requests=2.32.5=pyhcf101f3_1
  - ruff=0.12.0=py313h1361809_0
  - scikit-learn=1.7.1=py313hd8cff78_0
  - scikit-survival=0.26.0=np2py313h73f1cee_0
  - scipy=1.16.3=py313hbd6d557_0
  - setuptools=80.9.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - sqlalchemy=2.0.43=py313hda9a48d_0
  - sqlite=3.51.0=hda9a48d_0
  - sympy=1.14.0=py313haa95532_1
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - threadpoolctl=3.5.0=py313h4442805_1
  - tk=8.6.15=hf199647_0
  - torchmetrics=1.8.2=py313haa95532_0
  - torchsurv=0.1.5=pyhd8ed1ab_0
  - tqdm=4.67.1=py313h4442805_1
  - typing-extensions=4.15.0=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wfdb=4.3.0=pyhd8ed1ab_0
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - wrapt=2.0.1=py313h5ea7bf4_1
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py313hd650c13_0
  - zipp=3.23.0=py313haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
prefix: C:\Users\Luiz Alberto Freire\.conda\envs\isite
